### ISSUE TITLE
Increase the set of synced apis from googleapis/googleapis in the bsr

### ISSUE THREAD

**Issue by PeregrineFalcon** [bufbuild/modules#172]
## Mandatory

I am looking to use a wider set of the `googleapis/googleapis` that are synced in the bsr. Currently the bsr [includes a subset](https://buf.build/googleapis/googleapis) of:

https://github.com/googleapis/googleapis/tree/master/google

Specifically resources within `cloud/kms/v1` are omitted:
https://github.com/googleapis/googleapis/blob/master/google/cloud/kms/v1/resources.proto#L636

The package in particular is `google/cloud/kms/v1`. I would like to include some of these resources within our .proto types in order to return them via our gRPC service(s).

For example (PublicKey):
```
message GetPublicKeyResponse {
  google.cloud.kms.v1.PublicKey public_key = 1;
}
```

## Optional

**Does this module have other module dependencies/imports?**

Yes - it has quite a few dependencies. The good news is these are all already included in the bsr except one:

- `google/api` (already included)
- `google/longrunning` (already included)
- `google/rpc` (already included)
- `google/logging` (missing)

Some of these googleapis/googleapis are already synced. The suggestion would be to sync this wider set in the same manner.

I think anyone who wants to include these resources within their services within the wider community would find value in having these available on the bsr.

**Comment by smallsamantha** [comment]
Hey @PeregrineFalcon - we've discussed this internally and we are not going to add these packages to googleapis/googleapis at this time. For now, we'd suggest creating a BSR module with a copy of the protos you need and depend on the types in buf.build/googleapis/googleapis. Sorry for the inconvenience!
