### ISSUE TITLE
Managed Module request for Buf Schema Registry (grpc health service)

### ISSUE THREAD

**Issue by ahawker** [bufbuild/modules#285]
## Mandatory

**Where is the source code for the Managed Module?**

https://github.com/grpc/grpc-proto/tree/master

My current need is only https://github.com/grpc/grpc-proto/blob/master/grpc/health/v1/health.proto but not sure if makes sense to manage the entire thing.

**Do the proto files declare a package?**

Yes. [package grpc.health.v1](https://github.com/grpc/grpc-proto/blob/master/grpc/health/v1/health.proto#L20).

## Optional

**Does this module have other module dependencies/imports?**

Nope.

**Based on the repository's release process, do you prefer syncing by releases (semver) or by git commit SHA?**

Git commit SHA.

**Additionally, is there a sensible initial reference to sync from?**

HEAD should be fine. If not, [6565a1ba38af695ace7c3ce6e6ff837ee87d4c10](https://github.com/grpc/grpc-proto/commit/6565a1ba38af695ace7c3ce6e6ff837ee87d4c10) is the one I'm explicitly using (HEAD~1).

**Do you think this module is widely used by the community, and is not already provided on the BSR by the owners?**

Unsure how wide-spread it is but I doubt we're the only ones using this service definition for health checking.
Ref docs: https://github.com/grpc/grpc/blob/master/doc/health-checking.md

**Comment by pkwarren** [comment]
This module is already synchronized in this project - you can see it here in the public BSR: https://buf.build/grpc/grpc. It includes the health service as well as other gRPC protos.

**Comment by ahawker** [comment]
Ah, interesting. Even they note canonical version is the grpc-proto repo https://buf.build/grpc/grpc/file/main:grpc/health/v1/health.proto#L16.

No matter, i'll reference it from `grpc`. Thanks for the details and 👀 !
