### ISSUE TITLE
Module cncf/xds is not syncing: new dependency?

### ISSUE THREAD

**Issue by unmultimedio** [bufbuild/modules#339]
See https://github.com/bufbuild/modules/actions/workflows/fetch.yaml failed the last 3 times.

When processing reference `cncf/xds:0f5e0d9dbc1270b5eddd1be47fa8b2aea72f9a1f`, `buf build` fails because:

```
+ buf build
xds/type/v3/cel.proto:7:8:cel/expr/checked.proto: does not exist
```

That import `checked.proto` was added [here](https://github.com/cncf/xds/pull/75/files#diff-e4bf709ea291d58050fd2cde732d02307413ab4dc4ff59c49a065fad87503fc2R7), and then reverted [here](https://github.com/cncf/xds/pull/79) (although the PR says it will be reintroduced). Following now this issue: https://github.com/cncf/xds/issues/76

In the PR that introduced it, they also add `"@dev_cel//proto/cel/expr:checked_proto"`, to the BUILD bazel rules (which assume it translates to a new dependency that should go in the `buf.yaml`?)

I suspect that dep comes from here: https://github.com/google/cel-spec, although in that repo I don't see any `checked.proto` file.

Should we skip this commit? or make sure the dependency is synced before trying to sync `cncf/xds` again?

I'd appreciate your input here @rodaine @pkwarren

**Comment by unmultimedio** [comment]
For the moment being, I'll send a PR commenting that module to be able to keep syncing all the others.

**Comment by rodaine** [comment]
It's here: https://github.com/google/cel-spec/blob/master/proto/cel/expr/checked.proto
Or from googleapis: https://github.com/googleapis/googleapis/blob/master/google/api/expr/v1alpha1/checked.proto

Which I believe we are excluding from our subset of googleapis. If it's coming from there, we can add it back in  presumably. Otherwise, we'll need to add the appropriate dependency.

**Comment by unmultimedio** [comment]
Thanks! I think it's the first one, the containing dir matches, Idk why I didn't see it in my first search. I think we need to add that as another managed module to be able to use as a dependency then.

**Comment by unmultimedio** [comment]
Module `cncf/xds` is fetching new module versions again, as its new dependency `google/cel-spec` is now also being synced to the BSR as managed module: https://buf.build/google/cel-spec
