### ISSUE TITLE
Add managed module `planetscale/vitess`

### ISSUE THREAD

**Issue by smallsamantha** [bufbuild/modules#360]
## Mandatory

**Where is the source code for the Managed Module?**

https://github.com/planetscale/vitess-types

**Do the proto files declare a package?**

Yes, example https://github.com/planetscale/vitess-types/blob/main/src/vitess/vttime/v18/vttime.proto#L22

## Optional

**Does this module have other module dependencies/imports?**

**Based on the repository's release process, do you prefer syncing by releases (semver) or by git commit SHA?**

**Additionally, is there a sensible initial reference to sync from?**

**Do you think this module is widely used by the community, and is not already provided on the BSR by the owners?**

Unsure? Let's chat!

**Comment by unmultimedio** [comment]
This module is already being pushed to the BSR: https://buf.build/planetscale/vitess, here the `buf.yaml`: https://github.com/planetscale/vitess-types/blob/770e14433716a816905f267650191319f7d0515b/src/buf.yaml#L2

The owners have set up a GHA to sync main and non-main branches to the BSR: https://github.com/planetscale/vitess-types/blob/770e14433716a816905f267650191319f7d0515b/.github/workflows/publish.yml#L13

We want to have this module synced for all BSR clusters, including the public BSR? If so, we'd need to disable/ask the owners to disable such GHA.

For now I'll start making some progress on getting the CAS data here.

**Comment by unmultimedio** [comment]
Started fetching references from latest commit atm: `770e14433716a816905f267650191319f7d0515b` in #365. I will test this in a private test instance, and when that's successful we can ask the owners to turn off their GHA so we can start sending this up.

**Comment by unmultimedio** [comment]
Dropped from managed modules, since it's not required to be managed anymore.
