### ISSUE TITLE
Add managed module `bufbuild/reflect`

### ISSUE THREAD

**Issue by smallsamantha** [bufbuild/modules#361]
## Mandatory

**Where is the source code for the Managed Module?**

https://github.com/bufbuild/reflect-proto

**Do the proto files declare a package?**

Yes, already pushed via buf-push-action to BSR https://buf.build/bufbuild/reflect

## Optional

**Does this module have other module dependencies/imports?**

No

**Based on the repository's release process, do you prefer syncing by releases (semver) or by git commit SHA?**

git commit SHA

**Additionally, is there a sensible initial reference to sync from?**

TBD

**Comment by unmultimedio** [comment]
Setup complete. Module `bufbuild/reflect` is now being synced across BSR instances as managed module.
